### ISSUE TITLE
Using [[ and ]] inside the keyboard tag

### ISSUE THREAD

**Issue by kim366** [jGleitz/markdown-it-kbd#4]
> At the moment, “`[[`” and “`]]`” are not allowed within keystroke tags, because I can't think of a way to handle this that would make sense in all scenarios. If you think you know how it should be done, please file an issue!

What about escaping? So that would be `[[\]\]]]` and `[[\[\[]]` respectively. Not sure how one would implement this, though.

**Comment by jGleitz** [comment]
Hi! While this is a possibility, using backslashes for escaping seems un-markdown-ish and thus unexpected to me. Meanwhile, what does already work, is [using the HTML escape sequences for `[` and `]` (`&#91;` and `&#93;`)](https://runkit.com/jgleitz/5a99b45f30e35e0012a55c3c).

Do you need to use `[[` or `]]` inside `<kbd>`? Do you think using the HTML escape sequences is good enough solution?

**Comment by kim366** [comment]
Right, I actually like the html version better. I personally don't need it, just had the idea while reading your readme:)
